services:
  gradcam-app:
    build: .
    container_name: gradcam-flask
    ports:
      - "5000:5000"
    volumes:
      - ./models:/models:ro
    environment:
      MODEL_PATH: /models/Human_Face_Emotions/demo_stage-3.pkl